---
- name: restart tomcat
  ansible.builtin.systemd_service:
    name: tomcat
    daemon_reload: true
    enabled: true
    state: started
- name: Create a symbolic link
  ansible.builtin.file:
    src: "{{ homedir }}/apache-tomcat-{{ tomcat_specific_version }}"
    dest: "{{ homedir }}/latest"
    owner: "{{ username }}"
    group: "{{ groupname }}"
    state: link

