---
- name: install lamp server on ubuntu
  hosts: all
  become: yes
  vars:
    info_page_path: /var/www/html/info.php
  tasks:
    - name: install httpd server
      ansible.builtin.yum:
        name: "{{ package_name }}"
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
    - name: enable and start httpd
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        enabled: yes
        state: started
      when: ansible_facts['os_family'] == 'RedHat'
    - name: install httpd php server
      ansible.builtin.yum:
        name: php
        state: present
      notify:
        - restart apache
      when: ansible_facts['os_family'] == 'RedHat'
    - name: copy the info.php file in httpd
      ansible.builtin.copy:
        src: info.php
        dest: "{{ info_page_path }}"
      notify:
        - restart apache
      when: ansible_facts['os_family'] == 'RedHat'
    - name: update packages and install apache
      ansible.builtin.apt:
        name: "{{ package_name }}"
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == 'Ubuntu'
    - name: install php packages
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
      notify:
        - restart apache
      when: ansible_facts['os_family'] == 'Ubuntu'
    - name: copy the info.php page
      ansible.builtin.copy:
        src: info.php
        dest: "{{ info_page_path }}"
      notify:
        - restart apache
      when: ansible_facts['os_family'] == 'Ubuntu'
  handlers:
    - name: restart apache
      ansible.builtin.systemd:
        name: "{{ package_name }}"
        state: restarted
