---
- name: install lamp server on ubuntu
  hosts: ubuntu
  become: yes
  tasks:
    - name: update packages and install apache
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php packages
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
      notify:
        - restart apache2
    - name: copy the info.php page
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
      notify:
        - restart apache2
  handlers:
    - name: restart apache2
      ansible.builtin.systemd:
        name: apache2
        state: restarted
    
