---
- name: install tomcat
  hosts: tomcat
  become: yes
  tasks:
    - name: check if the playbook is being executed on supported os
      ansible.builtin.fail:
        msg: "This playbook is designed to work on ubuntu only"
      when: ansible_facts['distribution'] != "Ubuntu" 
    - name: install java
      ansible.builtin.apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: create group
      ansible.builtin.group:
        name: "{{ group }}"
        state: present
    - name: create user
      ansible.builtin.user:
        name: "{{ user }}"
        create_home: yes
        home: "{{ homedir }}"
        shell: "{{ shell }}"
        group: "{{ group }}"

      
    
      