---
# tasks file for default
- name: "update apt repo"
  apt:
    update_cache: yes
- name: install tomcat
  apt:
    name: "{{ package }}"
    state: "{{ st_to_be_set }}"
  notify:
  - restart tomcat
- name: change default settings
  template:
    src: tomcat7.j2
    dest: /etc/default/tomcat7
  notify:
    restart tomcat
  when: st_to_be_set == "present"
- name: install additional packages
  apt:
    name: {{ item }}
  with_items: 
    {{additional_packages }}
  when: st_to_be_set == "present"
- name: configure user for tomcat
  template:
    src: tomcat-users.xml.j2
    dest: /etc/tomcat7/tomcat-users.xml
  notify:
    restart tomcat
  when: st_to_be_set == "present"