---
username: tomcat
groupname: tomcat
homedir: /opt/tomcat
shell: /bin/false
tomcat_major_version: 10
tomcat_specific_version: 10.1.14
java_version: "11"
service_file_path: "/etc/systemd/system/tomcat.service"
tomcat_admin_username: admin
tomcat_admin_password: admin@123
allowed_ip_range: ".*"
