---
- name: install tomcat 10 on ubuntu
  hosts: ubuntu
  become: yes
  tasks:
    - name: update packages and install java
      ansible.builtin.apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: create a group tomcat
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present
    - name: create a system user tomcat
      ansible.builtin.user:
        name: "{{ user_name }}"
        create_home: true
        group: "{{ group_name }}"
        home: "{{ home_dir }}"
        shell: "{{ default_shell }}"
        state: present
    - name: download and extract tomcat
      ansible.builtin.unarchive:
        src: "https://www-eu.apache.org/dist/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ home_dir }}"
        remote_src: yes
