---
- name: install tomcat 10 on ubuntu
  hosts: ubuntu
  become: yes
  tasks:
    - name: update packages and install java 11
      ansible.builtin.apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
    - name: create a group tomcat
      ansible.builtin.group:
        name: "{{ group_name }}"
        state: present
    - name: create a system user tomcat
      ansible.builtin.user:
        name: "{{ user_name }}"
        create_home: true
        group: "{{ group_name }}"
        home: "{{ home_dir }}"
        shell: "{{ default_shell }}"
        state: present
