---
- name: install tomcat 10 on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: update packages and install java 11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: create a group tomcat
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create a system user tomcat
      ansible.builtin.user:
        name: tomcat
        create_home: true
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
